apiVersion: v1
kind: Pod
metadata:
  name: debugger
spec:
  containers:
  - name: debugger
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command: ["sh", "-c", "tail -f /dev/null"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
