apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: dev-app
  type: LoadBalancer
status:
  loadBalancer: {}
